# Generated by Django 3.0.3 on 2020-03-03 08:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='Field',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('type', models.CharField(max_length=100)),
                ('country', django_countries.fields.CountryField(max_length=2)),
                ('latitude', models.DecimalField(decimal_places=4, default=0.0, max_digits=6)),
                ('longitude', models.DecimalField(decimal_places=4, default=0.0, max_digits=6)),
            ],
        ),
        migrations.CreateModel(
            name='Isolate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isolate_id', models.CharField(max_length=100, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('taxa_name', models.CharField(max_length=200)),
                ('date_collected', models.DateField()),
                ('date_isolated', models.DateField()),
                ('country', django_countries.fields.CountryField(max_length=2)),
                ('tissue_type', models.CharField(max_length=100)),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='riceapp.Field')),
            ],
        ),
        migrations.CreateModel(
            name='People',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('full_name', models.CharField(max_length=100)),
                ('telephone_number', models.IntegerField()),
                ('designation', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='RiceBlastLab',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lab_id', models.CharField(max_length=100, unique=True)),
                ('lab_name', models.CharField(max_length=200)),
                ('country', django_countries.fields.CountryField(max_length=2)),
                ('institution', models.CharField(max_length=200)),
                ('principal_investigator', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='RiceGene',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('chromosome_id', models.IntegerField()),
                ('marker', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='RiceGenotype',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('rice_genotype_id', models.CharField(max_length=100, unique=True)),
                ('resistance_genes', models.CharField(max_length=200)),
                ('r_gene_sources', models.CharField(max_length=200)),
                ('susceptible_background', models.CharField(max_length=200)),
                ('accession_number', models.CharField(max_length=100)),
                ('pedigree', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('released_variety', 'Released Variety'), ('microgenic_line', 'Microgenic Line'), ('interspecific_variety', 'Interspecific Variety'), ('introgession_line', 'Introgession Line'), ('adapted_african_cultiva', 'Adapted African Cultiva')], max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='VcgGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.CharField(max_length=200)),
                ('vcg_id', models.CharField(max_length=100, unique=True)),
                ('lab', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='riceapp.RiceBlastLab')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='riceapp.People')),
            ],
        ),
        migrations.CreateModel(
            name='VCGTestResults',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vcg_test_id', models.CharField(max_length=100, unique=True)),
                ('vcg_tester_id', models.CharField(max_length=100)),
                ('tester_complimented_isolate', models.BooleanField()),
                ('tester_and_control', models.BooleanField()),
                ('vcg_replicate_id', models.CharField(max_length=100)),
                ('isolate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='riceapp.Isolate')),
                ('lab', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='riceapp.RiceBlastLab')),
                ('vcg', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='riceapp.VcgGroup')),
            ],
        ),
        migrations.CreateModel(
            name='RiceSmallDnaFragmentsSequence',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('taxa_name', models.CharField(max_length=200)),
                ('sequence_id', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('sequence_data', models.CharField(max_length=200)),
                ('chromosome_id', models.IntegerField()),
                ('chromosome_site_id', models.CharField(max_length=100)),
                ('loci_id', models.CharField(max_length=100)),
                ('target_gene', models.CharField(max_length=255)),
                ('lab', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='riceapp.RiceBlastLab')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='riceapp.People')),
                ('rice_genotype', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='riceapp.RiceGenotype')),
            ],
        ),
        migrations.CreateModel(
            name='RiceGeneScreenResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pcr_results', models.BooleanField()),
                ('replicate_id', models.CharField(max_length=20)),
                ('sample_id', models.CharField(max_length=100)),
                ('rice_gene', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='riceapp.RiceGene')),
            ],
        ),
        migrations.AddField(
            model_name='ricegene',
            name='rice_genotype',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='riceapp.RiceGenotype'),
        ),
        migrations.CreateModel(
            name='RiceGBS',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rice_gbs_name', models.CharField(max_length=200)),
                ('gbs_dataset', models.CharField(max_length=200)),
                ('lab', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='riceapp.RiceBlastLab')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='riceapp.People')),
            ],
        ),
        migrations.CreateModel(
            name='Protocol',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('protocol_id', models.CharField(max_length=100, unique=True)),
                ('key_reference', models.CharField(max_length=500)),
                ('protocol', models.CharField(max_length=200)),
                ('protocol_modified', models.DateField()),
                ('related_protocols', models.CharField(max_length=200)),
                ('country', django_countries.fields.CountryField(max_length=746, multiple=True)),
                ('lab', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='riceapp.RiceBlastLab')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='riceapp.People')),
            ],
        ),
        migrations.AddField(
            model_name='people',
            name='lab',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lab_people', to='riceapp.RiceBlastLab'),
        ),
        migrations.CreateModel(
            name='PathotypingResults',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('replicate_id', models.CharField(max_length=100)),
                ('sample_id', models.CharField(max_length=100)),
                ('stock_id', models.CharField(max_length=100)),
                ('date_inoculated', models.DateField()),
                ('date_scored', models.DateField()),
                ('date_planted', models.DateField()),
                ('disease_score', models.IntegerField()),
                ('test_id', models.CharField(max_length=100)),
                ('isolate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='riceapp.Isolate')),
                ('lab', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='riceapp.RiceBlastLab')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='riceapp.People')),
                ('rice_genotype', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='riceapp.RiceGenotype')),
            ],
        ),
        migrations.AddField(
            model_name='isolate',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='riceapp.People'),
        ),
        migrations.CreateModel(
            name='FungalSmallDnaFragmentsSequence',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('taxa_name', models.CharField(max_length=200)),
                ('sequence_id', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('sequence_data', models.CharField(max_length=200)),
                ('chromosome_id', models.IntegerField()),
                ('chromosome_site_id', models.CharField(max_length=100)),
                ('loci_id', models.CharField(max_length=100)),
                ('target_gene', models.CharField(max_length=255)),
                ('isolate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='riceapp.Isolate')),
                ('lab', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='riceapp.RiceBlastLab')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='riceapp.People')),
            ],
        ),
        migrations.CreateModel(
            name='FungalGBS',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fungal_gbs_name', models.CharField(max_length=200)),
                ('gbs_dataset', models.CharField(max_length=200)),
                ('lab', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='riceapp.RiceBlastLab')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='riceapp.People')),
            ],
        ),
        migrations.AddField(
            model_name='field',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='field_person', to='riceapp.People'),
        ),
    ]
