# Generated by Django 3.0.3 on 2020-02-23 18:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='Field',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('type', models.CharField(max_length=100)),
                ('country', django_countries.fields.CountryField(max_length=2)),
                ('latitude', models.DecimalField(decimal_places=4, default=0.0, max_digits=6)),
                ('longitude', models.DecimalField(decimal_places=4, default=0.0, max_digits=6)),
            ],
        ),
        migrations.CreateModel(
            name='Isolate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isolate_id', models.CharField(max_length=100, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('taxa_name', models.CharField(max_length=200)),
                ('date_collected', models.DateField()),
                ('date_isolated', models.DateField()),
                ('country', django_countries.fields.CountryField(max_length=2)),
                ('tissue_type', models.CharField(max_length=100)),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='riceapp.Field')),
            ],
        ),
        migrations.CreateModel(
            name='People',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('full_name', models.CharField(max_length=100)),
                ('telephone_number', models.IntegerField()),
                ('designation', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='RiceBlastLab',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lab_id', models.CharField(max_length=100, unique=True)),
                ('lab_name', models.CharField(max_length=200)),
                ('country', django_countries.fields.CountryField(max_length=2)),
                ('institution', models.CharField(max_length=200)),
                ('principal_investigator', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='RiceGenotype',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('rice_genotype_id', models.CharField(max_length=100, unique=True)),
                ('resistance_genes', models.CharField(max_length=200)),
                ('r_gene_sources', models.CharField(max_length=200)),
                ('susceptible_background', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='VcgGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.CharField(max_length=200)),
                ('vcg_id', models.CharField(max_length=100, unique=True)),
                ('lab', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='riceapp.RiceBlastLab')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='riceapp.People')),
            ],
        ),
        migrations.CreateModel(
            name='VCGTest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vcg_test_id', models.CharField(max_length=100, unique=True)),
                ('vcg_tester_id', models.CharField(max_length=100, unique=True)),
                ('tester_complimented_isolate', models.BooleanField()),
                ('vcg_replicate_id', models.CharField(max_length=100, unique=True)),
                ('isolate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='riceapp.Isolate')),
                ('lab', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='riceapp.RiceBlastLab')),
                ('vcg', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='riceapp.VcgGroup')),
            ],
        ),
        migrations.CreateModel(
            name='RiceGBS',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rice_gbs_name', models.CharField(max_length=200)),
                ('gbs_list', models.CharField(max_length=200)),
                ('gbs_dataset', models.CharField(max_length=200)),
                ('lab', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='riceapp.RiceBlastLab')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='riceapp.People')),
            ],
        ),
        migrations.CreateModel(
            name='Protocol',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('protocol_id', models.CharField(max_length=100, unique=True)),
                ('key_reference', models.CharField(max_length=200)),
                ('protocol', models.CharField(max_length=200)),
                ('protocol_modified', models.BooleanField()),
                ('related_protocols', models.CharField(max_length=200)),
                ('country', django_countries.fields.CountryField(max_length=746, multiple=True)),
                ('lab', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='riceapp.RiceBlastLab')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='riceapp.People')),
            ],
        ),
        migrations.AddField(
            model_name='people',
            name='lab',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lab_people', to='riceapp.RiceBlastLab'),
        ),
        migrations.CreateModel(
            name='PathotypingResults',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('replicate_id', models.CharField(max_length=100, unique=True)),
                ('sample_id', models.CharField(max_length=100, unique=True)),
                ('stock_id', models.CharField(max_length=100, unique=True)),
                ('date_inoculated', models.DateField()),
                ('date_scored', models.DateField()),
                ('date_planted', models.DateField()),
                ('disease_score', models.IntegerField()),
                ('test_id', models.CharField(max_length=100, unique=True)),
                ('isolate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='riceapp.Isolate')),
                ('lab', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='riceapp.RiceBlastLab')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='riceapp.People')),
                ('rice_genotype', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='riceapp.RiceGenotype')),
            ],
        ),
        migrations.AddField(
            model_name='isolate',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='riceapp.People'),
        ),
        migrations.AddField(
            model_name='field',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='field_person', to='riceapp.People'),
        ),
        migrations.CreateModel(
            name='DNASequence',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('taxa_name', models.CharField(max_length=200)),
                ('sequence_id', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField()),
                ('sequence_data', models.CharField(max_length=200)),
                ('chromosome_id', models.CharField(max_length=100, unique=True)),
                ('chromosome_site_id', models.CharField(max_length=100, unique=True)),
                ('loci_id', models.CharField(max_length=100, unique=True)),
                ('isolate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='riceapp.Isolate')),
                ('lab', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='riceapp.RiceBlastLab')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='riceapp.People')),
            ],
        ),
    ]
