# Generated by Django 3.0.3 on 2020-03-23 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('riceapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='isolate',
            name='isolate_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='isolate',
            name='isolate_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
