# Generated by Django 3.0.3 on 2020-03-10 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('riceapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pathotypingresults',
            name='tray',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
