# Generated by Django 3.0.3 on 2020-03-23 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('riceapp', '0002_auto_20200323_1403'),
    ]

    operations = [
        migrations.AlterField(
            model_name='isolate',
            name='collection_site',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='isolate',
            name='country',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='isolate',
            name='date_collected',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='isolate',
            name='host_genotype',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='isolate',
            name='taxa_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='isolate',
            name='tissue_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
