# Generated by Django 3.0.3 on 2020-03-04 08:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('riceapp', '0002_auto_20200304_1054'),
    ]

    operations = [
        migrations.AddField(
            model_name='ricegenescreenresult',
            name='rice_genotype',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='riceapp.RiceGenotype'),
            preserve_default=False,
        ),
    ]
