# Generated by Django 3.0.3 on 2020-11-17 12:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('riceapp', '0002_auto_20201117_1505'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='protocol',
            name='key_reference',
        ),
        migrations.RemoveField(
            model_name='protocol',
            name='lab',
        ),
        migrations.RemoveField(
            model_name='protocol',
            name='person',
        ),
        migrations.RemoveField(
            model_name='protocol',
            name='protocol_id',
        ),
        migrations.RemoveField(
            model_name='protocol',
            name='protocol_modified',
        ),
        migrations.RemoveField(
            model_name='protocol',
            name='related_protocols',
        ),
    ]
