# Generated by Django 3.0.3 on 2020-09-22 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('riceapp', '0002_auto_20200921_2002'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pathotypingresults',
            name='project',
        ),
        migrations.AlterField(
            model_name='pathotypingresults',
            name='date_inoculated',
            field=models.DateField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='pathotypingresults',
            name='date_planted',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='pathotypingresults',
            name='date_scored',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
