# Generated by Django 3.0.3 on 2020-03-23 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('riceapp', '0003_auto_20200323_1422'),
    ]

    operations = [
        migrations.AlterField(
            model_name='isolate',
            name='isolate_id',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
