# Generated by Django 3.0.3 on 2020-03-04 09:53

from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('riceapp', '0003_ricegenescreenresult_rice_genotype'),
    ]

    operations = [
        migrations.CreateModel(
            name='FungalCollectionSite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('type', models.CharField(max_length=100)),
                ('country', django_countries.fields.CountryField(max_length=2)),
                ('latitude', models.DecimalField(decimal_places=4, default=0.0, max_digits=6)),
                ('longitude', models.DecimalField(decimal_places=4, default=0.0, max_digits=6)),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='field_person', to='riceapp.People')),
            ],
        ),
        migrations.CreateModel(
            name='FungalGeneScreenResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fungal_gene', models.CharField(max_length=255)),
                ('pcr_results', models.CharField(max_length=100)),
                ('replicate_id', models.CharField(max_length=20)),
                ('sample_id', models.CharField(max_length=100)),
                ('rice_genotype', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='riceapp.RiceGenotype')),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=255)),
                ('donor', models.CharField(max_length=255)),
                ('start', models.DateField()),
                ('finish', models.DateField()),
                ('prinicipal_investigator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='riceapp.People')),
            ],
        ),
        migrations.RenameField(
            model_name='ricegene',
            old_name='rice_genotype',
            new_name='donor_line',
        ),
        migrations.RemoveField(
            model_name='isolate',
            name='field',
        ),
        migrations.RemoveField(
            model_name='protocol',
            name='country',
        ),
        migrations.AlterField(
            model_name='fungalgbs',
            name='gbs_dataset',
            field=models.FileField(upload_to='fungal_gbs_dataset'),
        ),
        migrations.AlterField(
            model_name='fungalsmalldnafragmentssequence',
            name='sequence_data',
            field=models.FileField(upload_to='fungal_sequence_data/'),
        ),
        migrations.AlterField(
            model_name='fungalsmalldnafragmentssequence',
            name='sequence_id',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='pathotypingresults',
            name='sample_id',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='ricegbs',
            name='gbs_dataset',
            field=models.FileField(upload_to='rice_gbs_dataset/'),
        ),
        migrations.AlterField(
            model_name='ricegenescreenresult',
            name='pcr_results',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='ricesmalldnafragmentssequence',
            name='sequence_data',
            field=models.FileField(upload_to='rice_sequence_data/'),
        ),
        migrations.AlterField(
            model_name='ricesmalldnafragmentssequence',
            name='sequence_id',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.DeleteModel(
            name='Field',
        ),
        migrations.AddField(
            model_name='fungalcollectionsite',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='riceapp.Project'),
        ),
        migrations.AddField(
            model_name='isolate',
            name='collection_site',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='riceapp.FungalCollectionSite'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pathotypingresults',
            name='project',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='riceapp.Project'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vcgtestresults',
            name='project',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='riceapp.Project'),
            preserve_default=False,
        ),
    ]
