# Generated by Django 3.0.3 on 2020-11-18 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('riceapp', '0003_auto_20201117_1531'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestFileUpload',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='fungalgbs',
            name='gbs_dataset',
            field=models.FileField(upload_to='fungal_gbs_dataset/'),
        ),
        migrations.AlterField(
            model_name='fungalsmalldnafragmentssequence',
            name='date_of_sequence',
            field=models.CharField(max_length=200),
        ),
    ]
