# Generated by Django 3.0.3 on 2020-09-22 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('riceapp', '0003_auto_20200922_2137'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pathotypingresults',
            name='date_inoculated',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
