# Generated by Django 3.0.3 on 2020-11-18 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('riceapp', '0004_auto_20201118_1148'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fungalgbs',
            name='gbs_dataset',
            field=models.FileField(upload_to='FungalGBS/fungal_gbs_dataset/'),
        ),
        migrations.AlterField(
            model_name='fungalsmalldnafragmentssequence',
            name='fungal_gene_sequence',
            field=models.FileField(upload_to='FungalSmallDnaFragmentsSequence/fungal_gene_sequence/'),
        ),
        migrations.AlterField(
            model_name='protocol',
            name='protocol',
            field=models.FileField(upload_to='Protocol/protocols/'),
        ),
        migrations.AlterField(
            model_name='ricegbs',
            name='gbs_dataset',
            field=models.FileField(upload_to='RiceGBS/rice_gbs_dataset/'),
        ),
        migrations.AlterField(
            model_name='ricesmalldnafragmentssequence',
            name='sequence_data',
            field=models.FileField(upload_to='RiceSmallDnaFragmentsSequence/rice_sequence_data/'),
        ),
    ]
