# Generated by Django 3.0.3 on 2020-04-02 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('riceapp', '0004_auto_20200323_1424'),
    ]

    operations = [
        migrations.AlterField(
            model_name='people',
            name='telephone_number',
            field=models.CharField(max_length=100),
        ),
    ]
