# Generated by Django 3.0.3 on 2020-03-04 11:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('riceapp', '0004_auto_20200304_1253'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ricegene',
            name='donor_line',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='riceapp.RiceGenotype'),
        ),
    ]
