# Generated by Django 3.0.3 on 2020-08-21 18:49

from django.db import migrations
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('riceapp', '0005_auto_20200402_2119'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pathotypingresults',
            options={'verbose_name_plural': 'Pathotyping Results'},
        ),
        migrations.AlterModelOptions(
            name='people',
            options={'verbose_name_plural': 'People'},
        ),
        migrations.AlterField(
            model_name='fungalcollectionsite',
            name='country',
            field=django_countries.fields.CountryField(default='KE', max_length=2),
        ),
    ]
