# Generated by Django 3.0.3 on 2020-11-18 10:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('riceapp', '0006_auto_20201118_1222'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fungalgbs',
            name='lab',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='riceapp.RiceBlastLab'),
        ),
        migrations.AlterField(
            model_name='fungalgbs',
            name='person',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='riceapp.People'),
        ),
        migrations.AlterField(
            model_name='ricegbs',
            name='lab',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='riceapp.RiceBlastLab'),
        ),
        migrations.AlterField(
            model_name='ricegbs',
            name='person',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='riceapp.People'),
        ),
    ]
