# Generated by Django 3.0.3 on 2020-08-21 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('riceapp', '0006_auto_20200821_2149'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fungalcollectionsite',
            name='type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
