# Generated by Django 3.0.3 on 2020-03-05 06:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('riceapp', '0007_auto_20200305_0911'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ricegene',
            name='donor_line',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='riceapp.RiceGenotype'),
            preserve_default=False,
        ),
    ]
