# Generated by Django 3.0.3 on 2021-03-01 10:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('riceapp', '0007_auto_20201118_1344'),
    ]

    operations = [
        migrations.AddField(
            model_name='ricegene',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='riceapp.Project'),
        ),
    ]
