# Generated by Django 3.0.3 on 2020-09-07 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('riceapp', '0007_auto_20200821_2200'),
    ]

    operations = [
        migrations.AlterField(
            model_name='isolate',
            name='date_isolated',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
