# Generated by Django 3.0.3 on 2020-03-05 06:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('riceapp', '0008_auto_20200305_0949'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ricegene',
            name='donor_line',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='riceapp.RiceGenotype'),
        ),
    ]
