# Generated by Django 3.0.3 on 2021-03-01 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('riceapp', '0008_ricegene_project'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ricegene',
            name='project',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
