# Generated by Django 3.0.3 on 2020-03-06 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('riceapp', '0009_auto_20200305_0950'),
    ]

    operations = [
        migrations.AddField(
            model_name='ricegene',
            name='reference',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ricegene',
            name='resistance_type',
            field=models.CharField(choices=[('complete', 'Complete'), ('partial', 'Partial')], default=1, max_length=50),
            preserve_default=False,
        ),
    ]
