# Generated by Django 3.0.3 on 2021-03-01 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('riceapp', '0010_auto_20210301_1416'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ricegenotype',
            name='pedigree',
            field=models.TextField(blank=True, null=True),
        ),
    ]
