# Generated by Django 3.0.3 on 2020-03-06 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('riceapp', '0011_auto_20200306_1553'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ricegenotype',
            name='rice_genotype_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
