# Generated by Django 3.0.3 on 2021-03-01 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('riceapp', '0011_auto_20210301_1424'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ricegene',
            name='resistance_type',
            field=models.CharField(blank=True, choices=[('Complete', 'Complete'), ('Partial', 'Partial')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='ricegenotype',
            name='category',
            field=models.CharField(blank=True, choices=[('released_variety', 'Released Variety'), ('microgenic_line', 'Microgenic Line'), ('interspecific_variety', 'Interspecific Variety'), ('introgession_line', 'Introgession Line'), ('adapted_african_cultiva', 'Adapted African Cultiva')], max_length=50, null=True),
        ),
    ]
