# Generated by Django 3.0.3 on 2020-03-09 12:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('riceapp', '0012_auto_20200306_1555'),
    ]

    operations = [
        migrations.AlterField(
            model_name='isolate',
            name='collection_site',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='riceapp.FungalCollectionSite'),
        ),
        migrations.AlterField(
            model_name='isolate',
            name='date_collected',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='isolate',
            name='date_isolated',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='isolate',
            name='person',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='riceapp.People'),
        ),
        migrations.AlterField(
            model_name='isolate',
            name='taxa_name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='isolate',
            name='tissue_type',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='ricegenotype',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
