# Generated by Django 3.0.3 on 2021-03-03 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('riceapp', '0012_auto_20210301_1638'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ricegene',
            name='project',
        ),
        migrations.AddField(
            model_name='ricegenotype',
            name='project',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
