# Generated by Django 3.0.3 on 2020-03-09 12:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('riceapp', '0013_auto_20200309_1537'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pathotypingresults',
            name='isolate',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='riceapp.Isolate'),
        ),
        migrations.AlterField(
            model_name='pathotypingresults',
            name='lab',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='riceapp.RiceBlastLab'),
        ),
        migrations.AlterField(
            model_name='pathotypingresults',
            name='person',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='riceapp.People'),
        ),
        migrations.AlterField(
            model_name='pathotypingresults',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='riceapp.Project'),
        ),
        migrations.AlterField(
            model_name='pathotypingresults',
            name='replicate_id',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='pathotypingresults',
            name='rice_genotype',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='riceapp.RiceGenotype'),
        ),
    ]
