# Generated by Django 3.0.3 on 2021-03-11 10:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('riceapp', '0014_auto_20210311_1233'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fungalcollectionsite',
            name='project',
        ),
    ]
