# Generated by Django 3.0.3 on 2021-03-13 21:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('riceapp', '0017_auto_20210314_0012'),
    ]

    operations = [
        migrations.RenameField(
            model_name='newsletters',
            old_name='publication',
            new_name='newsletter',
        ),
    ]
