# Generated by Django 3.0.3 on 2021-03-14 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('riceapp', '0018_auto_20210314_0022'),
    ]

    operations = [
        migrations.CreateModel(
            name='Minutes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('date', models.CharField(max_length=100)),
                ('minutes', models.FileField(upload_to='Minutes/minutes')),
            ],
            options={
                'verbose_name_plural': 'Minutes',
            },
        ),
    ]
