# Generated by Django 3.0.3 on 2021-03-14 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('riceapp', '0019_minutes'),
    ]

    operations = [
        migrations.CreateModel(
            name='Outreach',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('outreach', models.CharField(max_length=100)),
                ('date', models.CharField(max_length=100)),
                ('brief', models.TextField()),
                ('image', models.ImageField(upload_to='Outreach/images')),
            ],
            options={
                'verbose_name_plural': 'Outreach',
            },
        ),
    ]
