# Generated by Django 3.0.3 on 2021-03-20 13:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('riceapp', '0020_outreach'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PathotypingResults',
        ),
    ]
