# Generated by Django 3.0.3 on 2021-03-21 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('riceapp', '0022_pathotypingresults'),
    ]

    operations = [
        migrations.AlterField(
            model_name='minutes',
            name='title',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='newsletters',
            name='title',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='outreach',
            name='outreach',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='publications',
            name='title',
            field=models.TextField(),
        ),
    ]
