# Generated by Django 3.0.3 on 2021-03-21 18:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('riceapp', '0023_auto_20210321_1523'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='isolate',
            name='taxa_name',
        ),
    ]
