# Generated by Django 3.0.3 on 2021-03-22 11:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('riceapp', '0024_remove_isolate_taxa_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PathotypingResults',
        ),
    ]
