# Generated by Django 3.0.3 on 2021-03-22 11:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('riceapp', '0025_delete_pathotypingresults'),
    ]

    operations = [
        migrations.CreateModel(
            name='PathotypingResults',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('replicate_id', models.CharField(blank=True, max_length=100, null=True)),
                ('sample_id', models.CharField(blank=True, max_length=100, null=True)),
                ('stock_id', models.CharField(blank=True, max_length=100, null=True)),
                ('date_inoculated', models.CharField(blank=True, max_length=100, null=True)),
                ('date_scored', models.CharField(blank=True, max_length=100, null=True)),
                ('date_planted', models.CharField(blank=True, max_length=100, null=True)),
                ('disease_score', models.IntegerField(blank=True, null=True)),
                ('test', models.IntegerField(blank=True, null=True)),
                ('tray', models.CharField(blank=True, max_length=100, null=True)),
                ('isolate', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='riceapp.Isolate')),
                ('lab', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='riceapp.RiceBlastLab')),
                ('person', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='riceapp.People')),
                ('rice_genotype', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='riceapp.RiceGenotype')),
            ],
            options={
                'verbose_name_plural': 'Pathotyping Results',
            },
        ),
    ]
