# Generated by Django 3.0.3 on 2021-04-06 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('riceapp', '0026_pathotypingresults'),
    ]

    operations = [
        migrations.AddField(
            model_name='outreach',
            name='outreach_file',
            field=models.FileField(blank=True, null=True, upload_to='Outreach/outreach'),
        ),
        migrations.AlterField(
            model_name='outreach',
            name='image',
            field=models.ImageField(blank=True, upload_to='Outreach/images'),
        ),
    ]
