# Generated by Django 3.0.3 on 2021-04-15 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('riceapp', '0027_auto_20210406_1856'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pathotypingresults',
            name='test',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
