# Generated by Django 3.0.3 on 2021-04-15 14:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('riceapp', '0028_auto_20210415_1303'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fungalgenescreenresult',
            name='rice_genotype',
        ),
        migrations.AddField(
            model_name='fungalgenescreenresult',
            name='isolate',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='riceapp.Isolate'),
        ),
    ]
