# Generated by Django 3.0.3 on 2021-04-22 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('riceapp', '0029_auto_20210415_1730'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pathotypingresults',
            name='disease_score',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
