# Generated by Django 3.0.3 on 2021-04-23 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('riceapp', '0030_auto_20210422_2032'),
    ]

    operations = [
        migrations.AddField(
            model_name='people',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('user', 'User')], default='user', max_length=50),
        ),
    ]
